apiVersion: v1
kind: Service
metadata:
  name: backendservice
spec:
  type: LoadBalancer
  selector:
    app: backend
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080